### PR TITLE
Only one marker infowindow to be open at one time within the map

### PR DESCRIPTION
**Pull request by AbhiProjects**

### CODE REVIEW

**Comment by explooosion** [comment]
Thank you. This is useful. 🙂

**Comment by AbhiProjects** [comment]
By removing the `sendInfowindow` output emitter, we will not be able to support multiple markers within the same map, i.e A -> B and C -> D

**Comment by explooosion** [comment]
Do you have any exmaple or gif for this?
I don’t understand. 😨

Let me think.. 🤔

**Comment by AbhiProjects** [comment]
Sorry for the confusion. I should have elaborated the problem clearly. Your Gifs  perfectly describe the problem. I too ran into this issue before opting for the output emitter way. 
Great work in maintaining the module. My apologies for late replies.

**Pull request merged**
