### PR TITLE
Add new parameters to Directive

### PR DESCRIPTION
**Pull request by peploc-innocv**
add 'avoidFerries' and 'unitSystem' inputs to directive, give default value to 'avoidFerries', pass them to directionsService call

### CODE REVIEW

**Comment by oscarInnocv** [comment]
Hello, can you check this pull request please? @explooosion

**Comment by explooosion** [comment]
Hi, @peploc-innocv @oscarInnocv 
I missed the notification.
Thank you for your contribution.

**Review by explooosion — APPROVED** [review]

**Comment by oscarInnocv** [comment]
@explooosion can you notify when you will release the new npm package version? thanks in advance for your courtesy

**Comment by explooosion** [comment]
Hi, I have publish `v.0.8.8`

https://github.com/explooosion/Agm-Direction/releases/tag/0.8.8
https://www.npmjs.com/package/agm-direction/v/0.8.8

**Comment by peploc-innocv** [comment]
Tnx man! @explooosion

**Pull request merged**
